// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtp_JwqV0ugRylL-dqVlnFqNeHV9TqlZE',
    appId: '1:778676534722:web:86a3cf2afcdcefd653aa5b',
    messagingSenderId: '778676534722',
    projectId: 'fasum-app-2d5f0',
    authDomain: 'fasum-app-2d5f0.firebaseapp.com',
    databaseURL: 'https://fasum-app-2d5f0-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-2d5f0.appspot.com',
    measurementId: 'G-JDZPKET9NZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKlQVkpbgyLSB-nlSeHGPhDiSwQ_AM8L0',
    appId: '1:778676534722:android:b3529a09d92d5d8753aa5b',
    messagingSenderId: '778676534722',
    projectId: 'fasum-app-2d5f0',
    databaseURL: 'https://fasum-app-2d5f0-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-2d5f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvAGxqk6UPEyCVGFUnxPLyPrUe8L98Yrs',
    appId: '1:778676534722:ios:9416fbe32fbcdbb353aa5b',
    messagingSenderId: '778676534722',
    projectId: 'fasum-app-2d5f0',
    databaseURL: 'https://fasum-app-2d5f0-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-2d5f0.appspot.com',
    iosBundleId: 'com.example.fasumapk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvAGxqk6UPEyCVGFUnxPLyPrUe8L98Yrs',
    appId: '1:778676534722:ios:9416fbe32fbcdbb353aa5b',
    messagingSenderId: '778676534722',
    projectId: 'fasum-app-2d5f0',
    databaseURL: 'https://fasum-app-2d5f0-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-2d5f0.appspot.com',
    iosBundleId: 'com.example.fasumapk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtp_JwqV0ugRylL-dqVlnFqNeHV9TqlZE',
    appId: '1:778676534722:web:4b60b242c7a2934453aa5b',
    messagingSenderId: '778676534722',
    projectId: 'fasum-app-2d5f0',
    authDomain: 'fasum-app-2d5f0.firebaseapp.com',
    databaseURL: 'https://fasum-app-2d5f0-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-2d5f0.appspot.com',
    measurementId: 'G-BMPWQR97B3',
  );
}
